version: "3.9"

services:
  quarkus-app:
    image: eclipse-temurin:21-jdk
    container_name: quarkus-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["./mvnw", "quarkus:dev"]
